version: '3'
services:
  installer:
    container_name: installer
    image: node:20.4.0-alpine
    volumes:
      - ./:/home/node/duplo
    user: node
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/duplo
    entrypoint: npm i

  test:
    container_name: test
    image: node:20.4.0-alpine
    volumes:
      - ./:/home/node/duplo
    ports:
      - 1506:1506
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/duplo
    command: npm run dev
    depends_on:
      installer: 
        condition: service_completed_successfully